repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies: ["pydantic", "spacy", "python-docx"]
  - repo: local
    hooks:
      - id: validate-markdown
        name: validate-markdown
        entry: python scripts/validate_markdown.py
        language: python
        types: [markdown]
