repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies: ["pydantic", "spacy", "python-docx", "fastapi", "httpx", "pytest", "locust", "slowapi", "jsonschema"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "protocol_to_crf_generator", "-ll"]
        pass_filenames: false
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.128.0
    hooks:
      - id: semgrep-ci
  - repo: local
    hooks:
      - id: validate-markdown
        name: validate-markdown
        entry: python scripts/validate_markdown.py
        language: python
        additional_dependencies: ["pymarkdownlnt"]
        types: [markdown]
