site_name: Protocol to CRF Generator
site_description: Documentation for the Protocol to CRF Generator project.
site_author: Your Org
repo_url: https://github.com/your-org/protocol-to-crf-generator
site_url: https://fderuiter.github.io/protocol_to_crf_generator/
docs_dir: docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - toc
  - admonition
  - codehilite
nav:
  - Home: index.md
  - Documentation Table of Contents: spec/table-of-contents.md
  - Technical Plan: spec/technical-plan.md
  - Design: spec/design.md
  - Requirements: spec/requirements.md
  - GitHub Models: github_models.md
  - Prototyping with AI Models: prototyping_with_ai_models.md
  - Optimizing with Models: optimizing_with_models.md
  - Evaluating AI Models: evaluating_ai_models.md
  - Storing Prompts: storing_prompts.md
  - Integrating AI Models: integrating_ai_models.md
