site_name: Protocol to CRF Generator
site_description: Documentation for the Protocol to CRF Generator project.
site_author: Your Org
repo_url: https://github.com/your-org/protocol-to-crf-generator
site_url: https://fderuiter.github.io/protocol_to_crf_generator/
docs_dir: docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - toc
  - admonition
  - codehilite
nav:
  - Home: index.md
  - Documentation Table of Contents: spec/table-of-contents.md
  - Technical Plan: spec/technical-plan.md
  - Design: spec/design.md
  - Requirements: spec/requirements.md
  - Prompt Templates:
      - Unified Cleansing: prompt_templates/unified_data_cleansing.md
      - Governance Gap Analysis: prompt_templates/regulatory_gap_analysis.md
      - Architecture Blueprint: prompt_templates/future_proof_architecture_blueprint.md
