name: Controlled Terminology Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run update script
        run: |
          python protocol_to_crf_generator/ct_update.py --db-path terminology.sqlite
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update controlled terminology'
          branch: 'chore/ct-update-${{ github.run_number }}'
          title: 'chore: automated controlled terminology update'
          body: |
            Automated update of terminology.sqlite. Please review changes before merging.
          draft: true

