name: Rotate Secrets

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rotate Secrets
        run: python scripts/rotate_secrets.py --env-file deploy/.env --restart
