name: OWASP ZAP Scan

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ secrets.STAGING_URL }}
          fail_action: true
          cmd_options: '-a'
