name: OWASP ZAP Scan

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ secrets.STAGING_URL }}
          fail_action: true
          cmd_options: '-a -m 3'
